### PR TITLE
feat: Entrega Trabajo en clase

### PR DESCRIPTION
**Pull request by RenataOrzc**
se arreglaron los errores en el escrito

### CODE REVIEW

**Comment by Pepe-Chuy** [comment]
Correct

**Comment by Maria-Paula-PR** [comment]
everything looks correct I'll change some spelling

**Review by Pepe-Chuy — APPROVED** [review]
Looks great, I' would just make some minor adjustments on the notebooks folder

**Review by Maria-Paula-PR — COMMENTED** [review]
approved

**Pull request merged**
